name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 배포를 트리거하는 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3으로 업데이트

      - name: Setup Node.js
        uses: actions/setup-node@v4  # v3으로 업데이트
        with:
          node-version: '20'  # Node.js 20으로 업데이트

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Export Next.js app
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
